# Generated by Django 4.1.6 on 2023-04-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BussinessLocations", "0002_home"),
    ]

    operations = [
        migrations.AddField(
            model_name="home",
            name="count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="home",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
