# Generated by Django 4.1.6 on 2023-04-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BussinessLocations", "0004_mhd"),
    ]

    operations = [
        migrations.AddField(
            model_name="mhd",
            name="homes_in_proximity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="poi",
            name="homes_in_proximity",
            field=models.IntegerField(default=0),
        ),
    ]
